# Generated by Django 4.2.3 on 2023-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_username_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='memes_uploaded',
            field=models.IntegerField(default=0),
        ),
    ]
