# Generated by Django 4.2.3 on 2023-08-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='memes_uploaded',
        ),
    ]
