# Generated by Django 4.2.3 on 2023-08-27 01:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_memes_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='users/default_user.webp', force_format='Webp', keep_meta=True, null=True, quality=95, scale=None, size=None, upload_to='users/'),
        ),
    ]
