# Generated by Django 4.2.3 on 2023-08-30 19:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_options_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='users/default_user.webp', force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='users/'),
        ),
    ]
