# Generated by Django 4.2.3 on 2023-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
