# Generated by Django 4.2.3 on 2024-04-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_social_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
