# Generated by Django 4.2.3 on 2023-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_meme_meme_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='vote_ratio',
            new_name='sad_face',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='vote_total',
            new_name='smiley_face',
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('like', '+1'), ('unlike', '-1')], max_length=10),
        ),
    ]
