# Generated by Django 4.2.3 on 2023-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_rename_vote_ratio_meme_sad_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_img',
            field=models.ImageField(default='/static/images/memes/default.webp', upload_to=''),
        ),
    ]
