# Generated by Django 4.2.3 on 2023-08-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_alter_meme_meme_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_img',
            field=models.ImageField(default='memes/default.webp', upload_to='memes/'),
        ),
    ]
