# Generated by Django 4.2.3 on 2023-08-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_meme_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='description',
        ),
    ]
