# Generated by Django 4.2.3 on 2023-08-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_remove_meme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=22),
        ),
    ]
