# Generated by Django 4.2.3 on 2023-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_alter_meme_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
