# Generated by Django 4.2.3 on 2023-08-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0011_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
