# Generated by Django 4.2.3 on 2023-08-27 01:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='memes/default.webp', force_format='Webp', keep_meta=True, null=True, quality=95, scale=None, size=None, upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
