# Generated by Django 4.2.3 on 2023-08-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_options_alter_userprofile_user_img'),
        ('memes', '0013_alter_tag_options_alter_meme_meme_img_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='sad_face',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='smiley_face',
        ),
        migrations.AddField(
            model_name='meme',
            name='sad_face',
            field=models.ManyToManyField(related_name='sad_face', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='meme',
            name='smiley_face',
            field=models.ManyToManyField(related_name='smiley_face', to='users.userprofile'),
        ),
    ]
