# Generated by Django 4.2.3 on 2023-08-27 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_options_alter_userprofile_user_img'),
        ('memes', '0014_remove_meme_sad_face_remove_meme_smiley_face_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactEmail',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='meme',
            name='sad_face',
            field=models.ManyToManyField(blank=True, related_name='sad_face', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='smiley_face',
            field=models.ManyToManyField(blank=True, related_name='smiley_face', to='users.userprofile'),
        ),
    ]
