# Generated by Django 4.2.3 on 2023-08-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0016_comments_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
