# Generated by Django 4.2.3 on 2023-08-29 21:43

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0018_comment_rename_contactemail_contactform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='memes/default.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='memes/'),
        ),
    ]
