# Generated by Django 4.2.3 on 2023-08-30 19:09

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_user_img'),
        ('memes', '0019_alter_contactform_message_alter_meme_meme_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='memes/default.webp', force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='sad_face',
            field=models.ManyToManyField(blank=True, null=True, related_name='sad_face', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='smiley_face',
            field=models.ManyToManyField(blank=True, null=True, related_name='smiley_face', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='memes.tag'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
