# Generated by Django 4.2.3 on 2023-09-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_user_img'),
        ('memes', '0020_alter_contactform_email_alter_contactform_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='sad_face',
            field=models.ManyToManyField(blank=True, related_name='sad_face', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='smiley_face',
            field=models.ManyToManyField(related_name='smiley_face', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='tags',
            field=models.ManyToManyField(blank=True, to='memes.tag'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
