# Generated by Django 4.2.3 on 2024-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_social_facebook_and_more'),
        ('memes', '0021_alter_comment_user_alter_meme_sad_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='smiley_face',
            field=models.ManyToManyField(blank=True, related_name='smiley_face', to='users.userprofile'),
        ),
    ]
